### ISSUE TITLE
add logos for newly supported protocols in front page:

### ISSUE THREAD

**Issue by jcelerier** [OSSIA/ossia.github.io#38]
Spout: [spout.zeal.co](https://spout.zeal.co/)

Syphon: https://syphon.info/

NDI: https://www.ndi.tv/tools/

Enttec DMX: https://www.enttec.com/range/controls/dmx-usb-interfaces/

**Comment by aklevy** [comment]
Spout and DMX was already on the front page, though the url link for DMX was missing (fixed)
